# configs/dataset_config.yaml
emotion_mapping:
  0: "Angry"
  1: "Disgust" 
  2: "Fear"
  3: "Happy"
  4: "Sad"
  5: "Surprise"
  6: "Neutral"

dataset_merge:
  # How to handle class imbalances
  oversample_minority: True
  validation_split: 0.2